id: P007985
initial_creation_type: ocr
source_metadata:
  id: bdr:W21912
  title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་དཀའ་འགྲེལ་ལེགས་བཤད་ལུང་གི་རྒྱ་མཚོ
  author: ''
  volumes:
    56682f09017c493ca34ca7dfc76ad090:
      image_group_id: I4816
      title: ''
      volume_number: 1
      total_pages: 450
ebook_metadata:
  title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་དཀའ་འགྲེལ་ལེགས་བཤད་ལུང་གི་རྒྱ་མཚོ
  author: ''
  sku: P007985
  cover: cover.jpg
  layers:
  - pagination
